# Generated by Django 6.0.2 on 2026-02-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(choices=[('MORADOR', 'Morador'), ('ADMIN', 'Administrador')], default='MORADOR', max_length=20),
        ),
    ]
