# Generated by Django 6.0.2 on 2026-02-19 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_residuo', models.CharField(choices=[('PAPEL', 'Papel'), ('PLASTICO', 'Plástico'), ('VIDRO', 'Vidro'), ('METAL', 'Metal'), ('ORGANICO', 'Orgânico'), ('OUTROS', 'Outros')], max_length=20)),
                ('quantidade', models.FloatField()),
                ('data', models.DateField(auto_now_add=True)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
